name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'stub/**'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - '*.gradle'
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches/
            ~/.gradle/wrapper/dists/
            .gradle/
          key: ${{ hashFiles('gradle/wrapper/gradle-wrapper.properties') }}

      - name: Build with Gradle
        run: | 
          if [[ -n "${{ secrets.STORE_FILE }}" ]] && [[ -n "${{ secrets.STORE_PASSWORD }}" ]] && [[ -n "${{ secrets.KEY_ALIAS }}" ]] && [[ -n "${{ secrets.KEY_PASSWORD }}" ]]; then
            echo "${{ secrets.STORE_FILE }}" | base64 -d > stub/release.jks
            export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
            export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
            export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
          else
            export STORE_PASSWORD="android"
            export KEY_ALIAS="android"
            export KEY_PASSWORD="android"
          fi
          ./gradlew assemble

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Stub-APK
          path: stub/build/outputs/apk/**/stub-*.apk
