name: Build

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'app/**'
      - 'gradle/wrapper/gradle-wrapper.properties'
      - '*.gradle'
  workflow_dispatch:
    inputs:
      release:
        description: 'Release'
        type: boolean
        required: true
        default: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'gradle'

      - name: Build with Gradle
        run: | 
          if [[ -n "${{ secrets.STORE_FILE }}" ]] && [[ -n "${{ secrets.STORE_PASSWORD }}" ]] && [[ -n "${{ secrets.KEY_ALIAS }}" ]] && [[ -n "${{ secrets.KEY_PASSWORD }}" ]]; then
            echo "${{ secrets.STORE_FILE }}" | base64 -d > app/release.jks
            export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
            export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
            export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
          else
            export STORE_PASSWORD="android"
            export KEY_ALIAS="android"
            export KEY_PASSWORD="android"
          fi
          ./gradlew assembleRelease -q
          echo "version=$(grep versionName ./app/build.gradle | awk '{print $2}' | tr -d \")" >> $GITHUB_ENV
          echo "commit=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Upload built APKs
        uses: actions/upload-artifact@v3
        with:
          name: SampleProject(v${{ env.version }}@${{ env.commit }})
          path: app/build/outputs/apk/release/app-release*.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event.inputs.release == 'true'
        with:
          tag_name: v${{ env.version }}
          draft: true
          prerelease: false
          files: app/build/outputs/apk/release/app-release*.apk
